include: package:lints/recommended.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_super_parameters: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
